version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: laravel_db
    restart: always
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  node:
    image: node:18
    container_name: laravel_node
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "5173:5173"
    command: ["npm", "run", "dev"]

  supabase:
    image: supabase/postgres:latest
    container_name: supabase_db
    restart: always
    environment:
      - POSTGRES_PASSWORD=supersecret
      - POSTGRES_USER=supabase_admin
      - POSTGRES_DB=supabase
    ports:
      - "5433:5432"

volumes:
  pg_data:
